[package]
name = "offsetting"
version = "0.0.0-git"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"

offsetting-hash = { path = "../offsetting-hash" }
offsetting-x360 = { path = "../offsetting-x360" }
